#pragma once

#include <string>
#include <fstream>
#include <cctype>
#include <cinttypes>
#include <filesystem>
#include <cstring>
#include <regex>
#include <openssl/types.h>

#include "defs.hpp"


/**
 * INI Config file abstract base class
 */
class Config {
public:
    bool m_error{false};

    bool parse(const std::string& path);

protected:
    virtual bool set_key(const char* section, const char* key, const char* value) = 0;

    static int parse_bool(const char* str) {
        auto len = strlen(str);
        if (len == 4 && strcasecmp(str, "true"))
            return true;
        if (len == 5 && strcasecmp(str, "false"))
            return false;
        if (len >= 1) {
            if (str[0] == 'y' || str[0] == 't' || str[0] == 'Y' || str[0] == 'T' || str[0] == '1')
                return true;
            if (str[0] == 'n' || str[0] == 'f' || str[0] == 'N' || str[0] == 'F' || str[0] == '0')
                return false;
        }
        return -1;
    }
};

/**
 * Parse protocol server config file
 */
class FediyConfig : public Config {
public:
    // TODO move to /etc
    static constexpr const char* CONFIG_FILE_PATH = "/opt/fediy/config.ini";

    explicit FediyConfig(const std::string& path = CONFIG_FILE_PATH) {
        parse(path);
        set_defaults(); // call after parse
    }

    /// Where files are stored
    std::string m_data_dir{"/opt/fediy"};

    /// Domain where we're hosting the service
    char* m_hostname;

    /// Password salt that should not be changed
    // if we have a store with purchases we can give the user a key that only works with their salt
    // if they try to change their salt to that of another user they'll get locked out
    // install package generates admin account
    std::string m_salt;

    /// TCP port number to bind to
    int m_port{8848};

    /// Hint for the number of threads to use
    int m_concurrency{4};

    /// Server public key
    std::string m_public_key;

    /// Server private key
    EVP_PKEY* m_private_key{nullptr};

    // TODO request timeouts?

protected:
    bool set_key(const char* section, const char* key, const char* value) override;
    void set_defaults();

    /**
     * Example config.ini
     *
     * hostname=example.com
     * data_dir=/opt/fediy/data
     * salt=this value is generated by install script
     * port=8848
     * concurrency=4
     */
};

