name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-gcc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: build-gcc
        run: |
          echo "nproc = `nproc`"
          sudo apt-get install -y gcc-14 g++14 libboost-all-dev openssl nlohmann-json3-dev libsqlite3-dev 
          git submodule update --init -j`nproc`
          export CXX=g++-14
          export CC=gcc-14
          ./build.sh || exit 1
          rm -rf build
          ./build.sh debug || exit 1

  build-clang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: build-clang
        run: |
          echo "nproc = `nproc`"
          sudo apt-get install -y clang-19 clang++-19 libboost-all-dev openssl nlohmann-json3-dev libsqlite3-dev
          git submodule update --init -j`nproc`
          export CXX=clang++-19
          export CC=clang-19
          ./build.sh || exit 1
          rm -rf build
          ./build.sh debug || exit 1
